In [6]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [7]:
# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from autogluon.tabular import TabularPredictor
from sklearn.model_selection import train_test_split

pd.set_option('display.max_rows', 200)
pd.set_option('display.max_columns', None)

In [8]:
%autoreload
from pathlib import Path
import sys
root = Path().resolve().absolute().parent.parent
print(root)
sys.path.append(str(root))

from src.pipeline import Pipeline, BuilingIdsEnum
pipe = Pipeline()



/Users/matsalexander/Desktop/SolarEnergyImpact


In [9]:
building_a = pipe.get_data(BuilingIdsEnum.A)
building_b = pipe.get_data(BuilingIdsEnum.B)
building_c = pipe.get_data(BuilingIdsEnum.C)
combined_df = pd.concat([building_a, building_b, building_c])
# reset index
combined_df = combined_df.reset_index(drop=True)
# Perform the train-test split with stratification based on 'building_id'
train_data, test_data = train_test_split(
    combined_df,
    test_size=0.20,
    random_state=42,
    stratify=combined_df['building']
)

# select features
features = ["timestamp", "area", "temperature", "wind_speed", "cloud_fraction", "precipitation"]
target = "value_import"

train_data = train_data[features + [target]]
test_data = test_data[features + [target]]



In [10]:
train_data.head(100)

timestamp  area  temperature  wind_speed  cloud_fraction  \
21842 2023-08-16 04:00:00  1384         15.8         0.7             0.9   
28067 2024-05-01 13:00:00  1384         19.7         7.0             0.0   
18388 2024-05-30 05:00:00  1095         12.0         2.3             0.9   
26603 2024-03-01 13:00:00  1384          5.2         3.2             1.0   
24505 2023-12-05 03:00:00  1384         -7.7         4.0             0.5   
3265  2023-11-14 01:00:00  1167         -0.6         3.3             0.9   
5524  2024-02-16 04:00:00  1167          0.1         1.0             1.0   
9126  2024-07-15 06:00:00  1167         14.2         1.8             1.0   
14733 2023-12-29 22:00:00  1095        -10.4         0.5             0.9   
10130 2024-08-26 02:00:00  1167          9.7         3.0             1.0   
6510  2024-03-28 06:00:00  1167          3.1         1.4             1.0   
9120  2024-07-15 00:00:00  1167         12.3         0.9             0.8   
11288 2023-08-08 09:00:00  1095         15.4         0.3             1.0   
18653 2024-06-10 06:00:00  1095          7.6         0.8             0.9   
11286 2023-08-08 07:00:00  1095         15.2         1.5             0.9   
16835 2024-03-26 12:00:00  1095          2.3         0.6             1.0   
15787 2024-02-11 20:00:00  1095         -6.0         1.1             1.0   
8940  2024-07-07 12:00:00  1167         16.3         4.4             1.0   
12834 2023-10-11 19:00:00  1095          8.2         6.6             0.5   
11692 2023-08-25 05:00:00  1095         13.5         0.5             1.0   
6871  2024-04-12 07:00:00  1167          4.2         0.9             1.0   
23862 2023-11-08 08:00:00  1384          1.8         3.0             0.6   
3197  2023-11-11 05:00:00  1167         -2.4         1.0             0.9   
21888 2023-08-18 02:00:00  1384         16.0         3.7             0.5   
22951 2023-10-01 09:00:00  1384         11.2         1.7             0.6   
19398 2024-07-11 07:00:00  1095         15.1         0.5             0.9   
27544 2024-04-09 18:00:00  1384          8.3         6.3             1.0   
25066 2023-12-28 12:00:00  1384         -2.1         5.1             0.9   
2418  2023-10-09 18:00:00  1167          4.6         0.7             0.7   
29602 2024-07-04 12:00:00  1384         13.2         3.9             1.0   
11308 2023-08-09 05:00:00  1095         12.3         1.5             1.0   
5676  2024-02-22 12:00:00  1167          5.2         1.0             1.0   
4774  2024-01-15 22:00:00  1167        -15.4         0.8             0.9   
19680 2024-07-23 01:00:00  1095         15.6         0.3             0.9   
24159 2023-11-20 17:00:00  1384         -0.6         5.1             0.8   
9988  2024-08-20 04:00:00  1167         12.9         1.9             1.0   
25423 2024-01-12 09:00:00  1384         -4.3         2.2             0.9   
7597  2024-05-12 13:00:00  1167         22.5         3.2             0.1   
9955  2024-08-18 19:00:00  1167         15.0         1.0             0.1   
23847 2023-11-07 17:00:00  1384          2.9         1.7             0.6   
26698 2024-03-05 12:00:00  1384          4.3         6.9             0.2   
11785 2023-08-29 02:00:00  1095         10.7         0.3             0.0   
6085  2024-03-10 13:00:00  1167         -0.2         3.2             1.0   
26525 2024-02-27 07:00:00  1384          1.6         4.2             0.9   
24229 2023-11-23 15:00:00  1384          4.7         6.8             0.0   
11196 2023-08-04 13:00:00  1095         18.1         0.9             1.0   
17841 2024-05-07 10:00:00  1095         13.5         0.5             0.9   
5525  2024-02-16 05:00:00  1167          0.2         0.4             1.0   
1189  2023-08-19 13:00:00  1167         16.4         2.0             1.0   
17024 2024-04-03 09:00:00  1095          0.9         2.3             0.9   
25801 2024-01-28 03:00:00  1384          3.7         6.0             0.9   
14193 2023-12-07 10:00:00  1095         -9.1         0.6        

In [11]:
test_data.head(100)

timestamp  area  temperature  wind_speed  cloud_fraction  \
9584  2024-08-03 08:00:00  1167    18.800000    0.400000        0.900000   
11371 2023-08-11 20:00:00  1095    15.700000    1.400000        0.100000   
27936 2024-04-26 02:00:00  1384     3.600000    3.500000        0.900000   
17629 2024-04-28 14:00:00  1095     4.000000    2.800000        1.000000   
26934 2024-03-15 08:00:00  1384     5.000000    1.700000        1.000000   
22651 2023-09-18 21:00:00  1384    16.500000    6.300000        0.900000   
6907  2024-04-13 19:00:00  1167     8.800000    1.600000        0.900000   
18189 2024-05-21 22:00:00  1095    11.900000    0.800000        0.000000   
17999 2024-05-14 00:00:00  1095     7.800000    0.500000        0.700000   
11852 2023-08-31 21:00:00  1095    11.600000    0.600000        0.700000   
21322 2023-07-25 12:00:00  1384    21.700000    5.200000        0.000000   
26334 2024-02-19 08:00:00  1384    -0.500000    1.900000        0.900000   
20778 2023-07-02 20:00:00  1384    15.000000    0.700000        0.400000   
21690 2023-08-09 20:00:00  1384    14.200000    1.600000        0.900000   
4212  2023-12-23 12:00:00  1167   -13.000000    0.900000        0.000000   
11071 2023-07-30 08:00:00  1095    15.900000    0.600000        1.000000   
30848 2024-08-25 10:00:00  1384    16.300000    6.400000        0.300000   
29555 2024-07-02 13:00:00  1384    16.802222    2.466667        0.422222   
7083  2024-04-21 03:00:00  1167     0.200000    1.700000        0.000000   
28984 2024-06-08 18:00:00  1384    11.000000    4.700000        0.300000   
19817 2024-07-28 18:00:00  1095    21.200000    2.100000        0.000000   
20750 2023-07-01 16:00:00  1384    18.100000    3.500000        0.900000   
29501 2024-06-30 07:00:00  1384    14.400000    1.700000        0.900000   
16065 2024-02-23 10:00:00  1095     2.100000    2.600000        1.000000   
18378 2024-05-29 19:00:00  1095    16.400000    1.100000        0.200000   
24786 2023-12-16 20:00:00  1384     5.300000    3.200000        0.000000   
5016  2024-01-26 00:00:00  1167    -4.000000    0.400000        1.000000   
16985 2024-04-01 18:00:00  1095     7.300000    1.200000        0.200000   
11025 2023-07-28 10:00:00  1095    16.900000    0.900000        0.600000   
7667  2024-05-15 11:00:00  1167    22.100000    2.900000        0.900000   
15329 2024-01-23 18:00:00  1095    -0.900000    0.800000        0.900000   
30483 2024-08-10 05:00:00  1384    13.700000    4.600000        0.300000   
23572 2023-10-27 06:00:00  1384     1.900000    4.700000        0.800000   
19712 2024-07-24 09:00:00  1095    17.200000    2.600000        0.900000   
6852  2024-04-11 12:00:00  1167    16.900000    4.700000        0.000000   
17655 2024-04-29 16:00:00  1095    13.300000    2.900000        0.500000   
16765 2024-03-23 14:00:00  1095     7.700000    1.500000        1.000000   
11056 2023-07-29 17:00:00  1095    21.800000    2.600000        0.200000   
21654 2023-08-08 08:00:00  1384    15.700000    2.400000        1.000000   
11728 2023-08-26 17:00:00  1095    15.100000    2.500000        1.000000   
23614 2023-10-29 00:00:00  1384     1.300000    4.700000        0.900000   
30769 2024-08-22 03:00:00  1384    12.800000    4.200000        1.000000   
11216 2023-08-05 09:00:00  1095    15.500000    1.900000        1.000000   
30550 2024-08-13 00:00:00  1384    12.500000    0.300000        0.900000   
26568 2024-02-29 02:00:00  1384     4.500000    7.200000        1.000000   
4223  2023-12-23 23:00:00  1167   -16.100000    1.200000        0.500000   
1266  2023-08-22 18:00:00  1167    19.800000    1.200000        0.100000   
3040  2023-11-04 16:00:00  1167     3.600000    1.100000        1.000000   
3170  2023-11-10 02:00:00  1167    -2.900000    0.900000        0.900000   
6966  2024-04-16 06:00:00  1167    -0.600000    1.400000        0.500000   
19368 2024-07-10 01:00:00  1095     9.800000    0.600000        0.900000   
8172  2024-06-05 12:00:00  1167    16.100000    4.700000        

In [ ]:
# Train the model using AutoGluon
predictor = TabularPredictor(label=target, eval_metric='mean_absolute_error').fit(
    train_data, 
    presets='best_quality',
    excluded_model_types=['KNN']
    )

No path specified. Models will be saved in: "AutogluonModels/ag-20241109_111950"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.1.1
Python Version:     3.10.13
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
CPU Count:          10
Memory Avail:       15.00 GB / 32.00 GB (46.9%)
Disk Space Avail:   621.09 GB / 926.35 GB (67.0%)
Presets specified: ['best_quality']
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal 

[1000]	valid_set's l1: 6.07501
[2000]	valid_set's l1: 5.78648
[3000]	valid_set's l1: 5.6268
[4000]	valid_set's l1: 5.52069
[5000]	valid_set's l1: 5.44529
[6000]	valid_set's l1: 5.38433
[7000]	valid_set's l1: 5.34409
[8000]	valid_set's l1: 5.30283
[9000]	valid_set's l1: 5.273
[10000]	valid_set's l1: 5.2553
[1000]	valid_set's l1: 6.08035
[2000]	valid_set's l1: 5.80636
[3000]	valid_set's l1: 5.64797
[4000]	valid_set's l1: 5.53999
[5000]	valid_set's l1: 5.46072
[6000]	valid_set's l1: 5.40086


	Ran out of time, early stopping on iteration 6235. Best iteration is:
	[6235]	valid_set's l1: 5.38999


[1000]	valid_set's l1: 5.94994
[2000]	valid_set's l1: 5.68865
[3000]	valid_set's l1: 5.55142
[4000]	valid_set's l1: 5.45328
[5000]	valid_set's l1: 5.38454
[6000]	valid_set's l1: 5.32817


	Ran out of time, early stopping on iteration 6368. Best iteration is:
	[6364]	valid_set's l1: 5.30857


[1000]	valid_set's l1: 6.03209
[2000]	valid_set's l1: 5.74906
[3000]	valid_set's l1: 5.58594
[4000]	valid_set's l1: 5.48716
[5000]	valid_set's l1: 5.41051
[6000]	valid_set's l1: 5.35182


	Ran out of time, early stopping on iteration 6050. Best iteration is:
	[6031]	valid_set's l1: 5.35038


[1000]	valid_set's l1: 6.13137
[2000]	valid_set's l1: 5.83397
[3000]	valid_set's l1: 5.67315
[4000]	valid_set's l1: 5.55386
[5000]	valid_set's l1: 5.46717
[6000]	valid_set's l1: 5.40311


	Ran out of time, early stopping on iteration 6386. Best iteration is:
	[6384]	valid_set's l1: 5.38428


[1000]	valid_set's l1: 5.88699
[2000]	valid_set's l1: 5.58856
[3000]	valid_set's l1: 5.42108
[4000]	valid_set's l1: 5.30274
[5000]	valid_set's l1: 5.22316
[6000]	valid_set's l1: 5.16418
[7000]	valid_set's l1: 5.11578


	Ran out of time, early stopping on iteration 7383. Best iteration is:
	[7376]	valid_set's l1: 5.09959


[1000]	valid_set's l1: 6.05065
[2000]	valid_set's l1: 5.7566
[3000]	valid_set's l1: 5.58677
[4000]	valid_set's l1: 5.47299
[5000]	valid_set's l1: 5.39058
[6000]	valid_set's l1: 5.33536
[7000]	valid_set's l1: 5.28602
[8000]	valid_set's l1: 5.24346


	Ran out of time, early stopping on iteration 8182. Best iteration is:
	[8182]	valid_set's l1: 5.23508


[1000]	valid_set's l1: 5.99279
[2000]	valid_set's l1: 5.71728
[3000]	valid_set's l1: 5.54405
[4000]	valid_set's l1: 5.43052
[5000]	valid_set's l1: 5.35591
[6000]	valid_set's l1: 5.28894
[7000]	valid_set's l1: 5.25168
[8000]	valid_set's l1: 5.21839
[9000]	valid_set's l1: 5.18831


	Ran out of time, early stopping on iteration 9791. Best iteration is:
	[9716]	valid_set's l1: 5.16993
	-5.2741	 = Validation score   (-mean_absolute_error)
	571.83s	 = Training   runtime
	2.26s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 24.47s of the 324.58s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy
	Ran out of time, early stopping on iteration 191. Best iteration is:
	[191]	valid_set's l1: 5.07383
	Ran out of time, early stopping on iteration 203. Best iteration is:
	[203]	valid_set's l1: 5.03595
	Ran out of time, early stopping on iteration 239. Best iteration is:
	[239]	valid_set's l1: 5.00877
	Ran out of time, early stopping on iteration 257. Best iteration is:
	[257]	valid_set's l1: 4.9139
	Ran out of time, early stopping on iteration 270. Best iteration is:
	[270]	valid_set's l1: 5.03878
	Ran out of time, early stopping on iteration 285. Best iteration is:
	[285]	valid_set's l

[1000]	valid_set's l1: 5.92245
[2000]	valid_set's l1: 5.62969
[3000]	valid_set's l1: 5.46043
[4000]	valid_set's l1: 5.34185
[5000]	valid_set's l1: 5.25124
[6000]	valid_set's l1: 5.18188
[7000]	valid_set's l1: 5.13049
[8000]	valid_set's l1: 5.0891
[9000]	valid_set's l1: 5.05294
[10000]	valid_set's l1: 5.02345
[1000]	valid_set's l1: 6.0292
[2000]	valid_set's l1: 5.75662
[3000]	valid_set's l1: 5.58846
[4000]	valid_set's l1: 5.47182
[5000]	valid_set's l1: 5.38238
[6000]	valid_set's l1: 5.31468


In [ ]:
# Evaluate on test data
performance = predictor.evaluate(test_data)
# best model: ag-20241022_161331

print("Evaluation Performance:")
performance
# reset index 
test_data = test_data.reset_index(drop=True)
# To see feature importance
global_importance = predictor.feature_importance(test_data)
print("\nFeature Importance:")
print(global_importance)  # Shows which features had the most impact on model predictions


AssertionError: Trainer has no fit models that can infer.

In [ ]:
import numpy as np
matrix = []
size = 1000
for i in range(size):
    matrix.append([])
    for j in range(size):
        K = 1
        if i == j:
            K = 1
        else:
            K = 0
        matrix[i].append(K)
# print as np matrix
print(np.array(matrix))
        

[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


In [ ]:
# model location => AutogluonModels/ag-20241016_095906
main_building = pipe.get_data(BuilingIdsEnum.MAIN)

data_predict = main_building[features]
data_predict


timestamp  area  temperature  wind_speed  cloud_fraction  \
0     2023-07-01 00:00:00  1199         13.6         1.6             0.5   
1     2023-07-01 01:00:00  1199         13.2         2.0             0.4   
2     2023-07-01 02:00:00  1199         12.3         1.6             0.3   
3     2023-07-01 03:00:00  1199         11.9         0.6             0.9   
4     2023-07-01 04:00:00  1199         11.9         0.2             0.8   
...                   ...   ...          ...         ...             ...   
10338 2024-09-03 18:00:00  1199         17.8         2.5             1.0   
10339 2024-09-03 19:00:00  1199         17.8         1.8             1.0   
10340 2024-09-03 20:00:00  1199         17.7         1.1             1.0   
10341 2024-09-03 21:00:00  1199         18.0         3.4             1.0   
10342 2024-09-03 22:00:00  1199         17.9         3.0             1.0   

       precipitation  
0                0.0  
1                0.0  
2                0.0  
3                0.0  
4                0.0  
...              ...  
10338            1.4  
10339            2.5  
10340            2.6  
10341            2.9  
10342            2.7  

[10343 rows x 6 columns]

In [ ]:
prediciton1 = predictor.predict(data_predict)

In [ ]:
# save predicitons as a csv in data folder from root.
import datetime
from pathlib import Path


prediciton1_df = pd.DataFrame(prediciton1)
date_time = datetime.datetime.now().strftime("%Y%m%d")
my_path = Path().resolve().parent.parent / 'data'/ "pred" / date_time / 'prediction_drita.csv'
# create folder
my_path.parent.mkdir(parents=True, exist_ok=True)
prediciton1_df.to_csv(my_path, index=False)